# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmZjMjJhMTlmZjY5ZGUxOTM2ZmIzM2NhYmZkZmQyMjY3MTZmOTkwYjI3ODc5NGI2ZTEzZDdkNDMwNDVkZjc1YTljM2NiYjk0NTcxNGRkNGFlNGIyZmYwM2I5NzUwNDIzNWRmYjZmYmRlOTNlODkzMjZjNDA2OTBiYmUxNTJmOTY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
